In [153]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

# 生成1000000筆訓練資料
num_samples = 1000000

# 生成隨機整數資料，範圍為 [1, 1000]
data = np.random.randint(1, 10000, size=(num_samples, 3))

# 生成標籤，判斷三個整數相乘是否大於4294967295
print(np.prod(data, axis=1))
labels = ((np.prod(data, axis=1) < 0) | (np.prod(data, axis=1) > 4294967295)).astype(int)



[ 6041365920 55503781548  1869166116 ...  1772646876 39319650916
 49237034400]


In [152]:
#print counts of labels == 0
print(np.count_nonzero(labels == 0))


0


In [154]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
X_train, X_test, y_train, y_test = train_test_split(data, labels, test_size=0.2, random_state=42)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(800000, 3) (200000, 3) (800000,) (200000,)


In [155]:
# 輸入數據標準化
max_value = 10000
X_train_normalized = X_train / max_value
X_test_normalized = X_test / max_value

In [156]:
from tensorflow.keras import layers, models
# 定義神經網絡模型
model = models.Sequential()

# 輸入層
model.add(layers.InputLayer(input_shape=(3,)))

# 全連接層 (Dense Layer)
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(32, activation='relu'))

# 輸出層
model.add(layers.Dense(1, activation='sigmoid'))

# 編譯模型
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 打印模型摘要
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_15 (Dense)            (None, 64)                256       
                                                                 
 dense_16 (Dense)            (None, 32)                2080      
                                                                 
 dense_17 (Dense)            (None, 1)                 33        
                                                                 
Total params: 2,369
Trainable params: 2,369


Non-trainable params: 0
_________________________________________________________________


In [157]:
# 訓練模型
model.fit(X_train_normalized, y_train, epochs=10, batch_size=64)




Epoch 1/10
12500/12500 [==============================] - 17s 1ms/step - loss: 0.0420 - accuracy: 0.9857
Epoch 2/10
12500/12500 [==============================] - 17s 1ms/step - loss: 0.0135 - accuracy: 0.9947
Epoch 3/10
12500/12500 [==============================] - 17s 1ms/step - loss: 0.0112 - accuracy: 0.9953
Epoch 4/10
12500/12500 [==============================] - 17s 1ms/step - loss: 0.0105 - accuracy: 0.9956
Epoch 5/10
12500/12500 [==============================] - 17s 1ms/step - loss: 0.0100 - accuracy: 0.9957
Epoch 6/10
12500/12500 [==============================] - 16s 1ms/step - loss: 0.0095 - accuracy: 0.9958
Epoch 7/10
12500/12500 [==============================] - 17s 1ms/step - loss: 0.0090 - accuracy: 0.9962
Epoch 8/10
12500/12500 [==============================] - 17s 1ms/step - loss: 0.0088 - accuracy: 0.9962
Epoch 9/10
12500/12500 [==============================] - 16s 1ms/step - loss: 0.0086 - accuracy: 0.9963
Epoch 10/10
12500/12500 [==============================

In [158]:
# 評估模型
test_loss, test_acc = model.evaluate(X_test_normalized, y_test, verbose=2)
print('Test accuracy:', test_acc)

6250/6250 - 5s - loss: 0.0062 - accuracy: 0.9974 - 5s/epoch - 866us/step
Test accuracy: 0.9973750114440918


In [162]:
# 生成隨機整數資料，範圍為 [1, 1000]
data_test = np.random.randint(1, 20000, size=(num_samples, 3))

# 生成標籤，判斷三個整數相乘是否大於4294967295
output = ((np.prod(data_test, axis=1) < 0) | (np.prod(data_test, axis=1) > 4294967295)).astype(int)
data_test_normalized = data_test / 20000



In [163]:
# 預測
predictions = model.predict(data_test_normalized)
correct = 0
for i in range(len(predictions)):
    if(predictions[i] > 0.5):
        predictions[i] = 1
    else:
        predictions[i] = 0

    if predictions[i] == output[i]:
        correct += 1
    else:
        print(data_test[i],output[i],predictions[i])
print('Accuracy: %f' % ((correct / float(len(predictions))) * 100.0))


31250/31250 [==============================] - 18s 572us/step
[5932  228 3966] 1 [0.]
[2765 1055 7107] 1 [0.]
[6003  298 9590] 1 [0.]
[10129  8642   330] 1 [0.]
[ 4843   259 15690] 1 [0.]
[1853  660 5695] 1 [0.]
[14836   152  7991] 1 [0.]
[ 5845   336 10693] 1 [0.]
[2331 5613 2425] 1 [0.]
[ 3492 16268   377] 1 [0.]
[10358   224 11749] 1 [0.]
[  626 17905  1487] 1 [0.]
[12533  2833   652] 1 [0.]
[2325  560 5488] 1 [0.]
[ 1195 10228  2127] 1 [0.]
[ 563 1821 7816] 1 [0.]
[1992 3401  940] 1 [0.]
[2841 5879 1929] 1 [0.]
[9739 1409  950] 1 [0.]
[13722  7283   104] 1 [0.]
[10873  5249   211] 1 [0.]
[6367 1283 3360] 1 [0.]
[11280   259  9054] 1 [0.]
[ 2761   843 10053] 1 [0.]
[8454 5149  544] 1 [0.]
[18650  1164   670] 1 [0.]
[ 760 7947 2945] 1 [0.]
[   90  7579 16566] 1 [0.]
[5670 4028 1021] 1 [0.]
[ 658 9636 4316] 1 [0.]
[6336 1740  652] 1 [0.]
[2445 5761  976] 1 [0.]
[14626    69 16573] 1 [0.]
[ 6715 17075   158] 1 [0.]
[ 819  976 9265] 1 [0.]
[2256 9442  414] 1 [0.]
[  651  1415 10433] 1 [

In [225]:
input = np.array([[4294967295,32323221,332322323]])
print(  ((np.prod(input, axis=1) < 0) | (np.prod(input, axis=1) > 4294967295)).astype(int))
input_normalized = input / 4294967295
print(input_normalized)
print(model.predict(input_normalized))


[1]
[[1.         0.00752584 0.07737482]]
1/1 [==============================] - 0s 12ms/step
[[8.916319e-19]]


In [136]:
print(correct)

980067
