In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np



2024-02-21 14:33:46.650906: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-21 14:33:46.755361: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-02-21 14:33:47.146225: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.2/lib64:
2024-02-21 14:33:47.146289: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: ca

In [ ]:
# 生成1000000筆訓練資料
#method 1 to generate data
low1 = 1
high1 = 2000
low2 = 2000
high2 = 4294967295
num_samples = 1000000
num_samples1 =int(1000000 * 0.5)
num_samples2 = int(1000000 * 0.5)
# 生成隨機整數資料，範圍為 [1, 1000]
#data = np.random.randint(1, 10000, size=(num_samples, 3))
samples1 = np.random.uniform(low1, high1, size=(num_samples1, 3))
samples2 = np.random.uniform(low2, high2, size=(num_samples2, 3))
#print(samples1)
#print(samples2)
data = np.concatenate((samples1, samples2))
#print(data)
# 生成標籤，判斷三個整數相乘是否大於4294967295
print(np.prod(data, axis=1))
labels = ((np.prod(data, axis=1) < 0) | (np.prod(data, axis=1) > 4294967295)).astype(int)
print(labels)

In [93]:
#method 2 to generate data
num_samples = 10000000
first1 = np.random.uniform(1, 2000, size=num_samples)
first2 = np.random.uniform(1, 2000, size=num_samples)
first3_1 = np.random.uniform(1, 4294967295, size=int(num_samples*0.2))
first3_2 = np.random.uniform(1, 2000, size=int(num_samples*0.4))
first3_3 = np.random.uniform(1, 2000000, size=int(num_samples*0.4))
first3 = np.concatenate((first3_1, first3_2, first3_3))

data = np.column_stack((first1, first2, first3))


print(data)
# 對每個樣本中的三個數字進行排序（從大到小）
data = np.sort(data, axis=-1)[:, ::-1]

# 打印排序後的數據
print(data)

[[1.23299266e+03 1.63176648e+03 1.17908793e+09]
 [1.14029799e+03 1.65098462e+03 3.97776976e+08]
 [1.80059120e+03 1.06836339e+03 2.09888422e+09]
 ...
 [1.38625710e+03 1.76538961e+03 1.30326788e+06]
 [1.37185533e+03 7.85095836e+02 1.97399646e+05]
 [9.64920963e+02 4.43799839e+02 1.19754109e+06]]
[[1.17908793e+09 1.63176648e+03 1.23299266e+03]
 [3.97776976e+08 1.65098462e+03 1.14029799e+03]
 [2.09888422e+09 1.80059120e+03 1.06836339e+03]
 ...
 [1.30326788e+06 1.76538961e+03 1.38625710e+03]
 [1.97399646e+05 1.37185533e+03 7.85095836e+02]
 [1.19754109e+06 9.64920963e+02 4.43799839e+02]]


In [2]:
#method 3 to generate data
import math
import random
num_samples = 10000000
data = []
for i in range(0,num_samples):
        ratio1 = random.randint(1,10)
        ratio2 = random.randint(1,10)
        ratio3 = random.randint(1,10)
        int1 = random.randint(1,10**ratio1)
        int2 = random.randint(1,10**ratio2)
        int3 = random.randint(1,10**ratio3)
        data +=[[int1,int2,int3]]
        #result3 +=[[int(math.log10(int1)+1) + int(math.log10(int2)+1) +int(math.log10(int3)+1)]]
        #result2 +=[[int1*int2*int3]]
        #int1 = int1/10**int(math.log10(int1)+1)
        #int2 = int2/10**int(math.log10(int2)+1)
        #int3 = int3/10**int(math.log10(int3)+1)
        #result1 +=[[int1,int2,int3]]

In [3]:
data = np.sort(data, axis=-1)[:, ::-1]
print(data)

[[ 472960840      45751        823]
 [   4608856     223253          1]
 [    298654        787        200]
 ...
 [      7790         93         52]
 [5655175641      47302      15270]
 [4813764265 1750834038    7133302]]


In [4]:
print(np.prod(data, axis=1))
labels = ((np.prod(data, axis=1) < 0) | (np.prod(data, axis=1) > 4294967295)).astype(int)
print(labels)
print(np.count_nonzero(labels == 0))

[   17808429034661320        1028940928568          47008139600 ...
             37672440  4084742074464787140 -8706980340420357628]
[1 1 1 ... 0 1 1]
1390442


In [5]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
X_train, X_test, y_train, y_test = train_test_split(data, labels, test_size=0.2, random_state=42)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(8000000, 3) (2000000, 3) (8000000,) (2000000,)


In [6]:
# 輸入數據標準化
max_value = 4294967295
X_train_normalized = X_train / max_value
X_test_normalized = X_test / max_value

In [13]:
from tensorflow.keras import layers, models
# 定義神經網絡模型
model = models.Sequential()

# 輸入層
model.add(layers.InputLayer(input_shape=(3,)))

# 全連接層 (Dense Layer)
model.add(layers.Dense(1000, activation='relu'))
model.add(layers.Dense(500, activation='relu'))
model.add(layers.Dense(250, activation='relu'))
# 輸出層
model.add(layers.Dense(1, activation='sigmoid'))

# 編譯模型
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 打印模型摘要
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_11 (Dense)            (None, 1000)              4000      
                                                                 
 dense_12 (Dense)            (None, 500)               500500    
                                                                 
 dense_13 (Dense)            (None, 250)               125250    
                                                                 
 dense_14 (Dense)            (None, 1)                 251       
                                                                 
Total params: 630,001
Trainable params: 630,001
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.fit(X_train_normalized, y_train, epochs=10, batch_size=64)

Epoch 1/10
125000/125000 [==============================] - 214s 2ms/step - loss: 0.1760 - accuracy: 0.9239
Epoch 2/10
125000/125000 [==============================] - 208s 2ms/step - loss: 0.1513 - accuracy: 0.9362
Epoch 3/10
125000/125000 [==============================] - 211s 2ms/step - loss: 0.1406 - accuracy: 0.9398
Epoch 4/10
125000/125000 [==============================] - 210s 2ms/step - loss: 0.1336 - accuracy: 0.9422
Epoch 5/10
125000/125000 [==============================] - 189s 2ms/step - loss: 0.1288 - accuracy: 0.9438
Epoch 6/10
125000/125000 [==============================] - 178s 1ms/step - loss: 0.1232 - accuracy: 0.9460
Epoch 7/10
125000/125000 [==============================] - 177s 1ms/step - loss: 0.1204 - accuracy: 0.9471
Epoch 8/10
125000/125000 [==============================] - 181s 1ms/step - loss: 0.1162 - accuracy: 0.9489
Epoch 9/10
125000/125000 [==============================] - 181s 1ms/step - loss: 0.1150 - accuracy: 0.9494
Epoch 10/10
125000/125000 [=

In [15]:
test_loss, test_acc = model.evaluate(X_test_normalized, y_test, verbose=2)
print('Test accuracy:', test_acc)

62500/62500 - 67s - loss: 0.0980 - accuracy: 0.9568 - 67s/epoch - 1ms/step
Test accuracy: 0.9567769765853882


In [19]:
# 生成隨機整數資料，範圍為 [1, 1000]
data_test = np.random.randint(1, 4294967295, size=(1000000, 3))
data_test = np.sort(data_test, axis=-1)[:, ::-1]
# 生成標籤，判斷三個整數相乘是否大於4294967295
output = ((np.prod(data_test, axis=1) < 0) | (np.prod(data_test, axis=1) > 4294967295)).astype(int)
data_test_normalized = data_test / 4294967295


In [20]:
# 預測
predictions = model.predict(data_test_normalized)
correct = 0
for i in range(len(predictions)):
    if(predictions[i] > 0.5):
        predictions[i] = 1
    else:
        predictions[i] = 0

    if predictions[i] == output[i]:
        correct += 1
    else:
        print(data_test[i],output[i],predictions[i])
print('Accuracy: %f' % ((correct / float(len(predictions))) * 100.0))
print(correct)


31250/31250 [==============================] - 29s 931us/step
Accuracy: 100.000000
1000000


In [26]:
input = np.array([[43324,1323,1232]])
np.sort(input, axis=-1)[:, ::-1]
print(  ((np.prod(input, axis=1) < 0) | (np.prod(input, axis=1) > 4294967295)).astype(int))
input_normalized = input / 4294967295
print(input_normalized)
print(model.predict(input_normalized))


[1]
[[1.00871548e-05 3.08034942e-07 2.86847353e-07]]
1/1 [==============================] - 0s 15ms/step
[[0.12883817]]


In [27]:
model.save('CVE2023-v3.h5')
