In [1]:
import numpy as np
from keras.models import load_model
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model
import tensorflow as tf
import random

2024-02-20 15:27:36.174377: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-20 15:27:36.270283: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-02-20 15:27:36.610207: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.2/lib64:
2024-02-20 15:27:36.610263: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: ca

In [12]:
model = tf.keras.models.load_model('CVE2023.h5')
model_v2 = tf.keras.models.load_model('CVE2023-v2.h5')

In [13]:
model.summary()
model_v2.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 3)]               0         
                                                                 
 dense_4 (Dense)             (None, 3000)              12000     
                                                                 
 dense_5 (Dense)             (None, 3000)              9003000   
                                                                 
 dense_6 (Dense)             (None, 3000)              9003000   
                                                                 
 dense_7 (Dense)             (None, 1)                 3001      
                                                                 
Total params: 18,021,001
Trainable params: 18,021,001
Non-trainable params: 0
_________________________________________________________________
Model: "sequential_2"
_________________________

In [4]:
#generate float random number

# def get_rand (size):
#     result1 = []
#     result2 = []
#     t = 1
#     for n2 in range (0,size):
#         value1 = random.random()
#         value2 = random.random()
#         value3 = random.random()
#         t = min(t,value1,value2,value3)
#         result1 += [[value1, value2, value3]]
#         result2 += [[value1*value2*value3]]
#     print(t)
#     return np.array(result1),np.array(result2)
# def root_mean_squared_error(actual, predicted):
#     mse = ((actual - predicted) ** 2).mean()
#     rmse = np.sqrt(mse)
#     return rmse
# def rand_test (constx):
#     x , ans= get_rand(constx)
#     print("x = ",x)
#     y = model.predict(x)
#     for i in range(0,constx):
#         print(y[i], ans[i], root_mean_squared_error(ans[i],y[i]))

In [5]:
model.predict(np.array([[0.1,0.2,0.3]]))

1/1 [==============================] - 1s 538ms/step


2024-02-20 15:27:53.595477: I tensorflow/stream_executor/cuda/cuda_blas.cc:1614] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.


array([[0.00648151]], dtype=float32)

In [6]:
# rand_test(10000)

1.6598532347700257e-05
x =  [[0.07450292 0.21832932 0.46432763]
 [0.2871876  0.6931472  0.61640643]
 [0.65292098 0.90233769 0.97966473]
 ...
 [0.23330366 0.99600317 0.80922746]
 [0.17416719 0.9870994  0.90506396]
 [0.06966409 0.00577121 0.19798954]]
313/313 [==============================] - 0s 795us/step
[0.00827792] [0.00755283] 0.000725089825684597
[0.12321715] [0.12270388] 0.0005132658656020056
[0.5787461] [0.57717458] 0.0015715044708812798
[0.05231811] [0.05174024] 0.0005778750197428587
[0.03518316] [0.0345478] 0.0006353572885219178
[0.27757287] [0.27637517] 0.0011976971819913085
[0.46917653] [0.46728992] 0.0018866102487593017
[0.08752136] [0.08684049] 0.0006808655828167143
[0.08225289] [0.08166584] 0.000587053780529867
[0.04019663] [0.03974841] 0.00044822649379124
[0.00702025] [0.0063276] 0.0006926463356356207
[0.10825931] [0.10737456] 0.000884753550824624
[0.04022513] [0.03934821] 0.0008769247939157815
[0.00100869] [2.91800694e-05] 0.000979509334108299
[0.00109087] [0.00043856] 

In [14]:
import math
n = 4294967295
print(n/10**int(math.log10(n)+1))

0.4294967295


In [8]:
def test_overflow(input):
    #print(input[0])
    if input[0] > 4294967295:
        return 1
    else:
        return 0
def run_test(input1,input2,size):
    suss = 0
    for i in range(0,size):
        if(test_overflow(input1[i]) == test_overflow(input2[i])):
            suss = suss+ 1
        else:
            print(input1[i],input2[i])
    return suss
def get_int_rand(n):
    result1=[]
    result2=[]
    result3=[]
    #print(n)
    for i in range(0,n):
        ratio1 = random.randint(1,10)
        ratio2 = random.randint(1,10)
        ratio3 = random.randint(1,10)
        int1 = random.randint(1,10**ratio1)
        int2 = random.randint(1,10**ratio2)
        int3 = random.randint(1,10**ratio3)
        result3 +=[[int(math.log10(int1)+1) + int(math.log10(int2)+1) +int(math.log10(int3)+1)]]
        result2 +=[[int1*int2*int3]]
        int1 = int1/10**int(math.log10(int1)+1)
        int2 = int2/10**int(math.log10(int2)+1)
        int3 = int3/10**int(math.log10(int3)+1)
        result1 +=[[int1,int2,int3]]
    return np.array(result1),np.array(result2),np.array(result3)


        

In [9]:
from decimal import Decimal, getcontext
getcontext().prec = 50
def int_rand_test (constx):
    x , ans, offset= get_int_rand(constx)
    #print("x = ",x)
    #print(offset)
    z=[]
    y = model.predict(x)
    for i in range(0,constx):
        #z = y[i]* (10**offset[i])
        off = float(Decimal('10') **offset[i])
        z +=[[y[i]*off]]
        #print(z[i], ans[i],int(math.log10(z[i][0])),int(math.log10(ans[i])))
    print("pass case number == ",run_test(z,ans,constx))

In [10]:
int_rand_test(10000)

313/313 [==============================] - 0s 720us/step
[array([4.32358e+09], dtype=float32)] [4283612475]
[array([4.3136067e+09], dtype=float32)] [4260616704]
pass case number ==  9998


/tmp/ipykernel_185525/71367164.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  off = float(Decimal('10') **offset[i])


In [15]:
model_v2.predict(np.array([[0.1,0.2,0.3]]))

1/1 [==============================] - 0s 28ms/step


array([[1.]], dtype=float32)