In [92]:
import numpy as np
import math
# x = random from 1 to 4294967295, 2 columns
origin_data =[]
data_x = []
offset = []
data_size = 1000000
for i in range(data_size):
    #random 1 to 10
    x = np.random.randint(1, 10)
    y = np.random.randint(1, 10)
    x = np.random.randint(1, 10**x)
    y = np.random.randint(1, 10**y)
    off = max(int(math.log10(x)+1), int(math.log10(y)+1))
    offset.append(off)
    #data.first should >= data.second
    if x < y:
        x, y = y, x
    origin_data.append([x, y])
    data_x.append([x/10**off, y/10**off])
offset = np.array(offset)
print(offset)
#print(data_x)
#print(origin_data)
#normalize data
data_x = np.array(data_x)
#data_y = data_x.first + data_x.second
data_y = np.sum(data_x, axis=1)
#print(data_x)
#print(data_y)
# data_x = np.random.randint(1, 4294967295, (1000000, 2))
# data_y = np.sum(x, axis=1)
# #normalize data
# data_x = data_x / 4294967295
# data_y = data_y / 4294967295
# #count y < 4294967295
# print(np.sum(y < 4294967295))
# #print size of x
# print(data_x)





[6 8 9 ... 8 8 4]


In [93]:
print(data_x)
print(data_y)

[[2.56924000e-01 1.75300000e-03]
 [2.27966170e-01 6.75570000e-04]
 [8.46549872e-01 5.00000000e-09]
 ...
 [2.37133480e-01 3.38441900e-02]
 [2.04627200e-01 7.35900000e-05]
 [2.10300000e-01 1.85400000e-01]]
[0.258677   0.22864174 0.84654988 ... 0.27097767 0.20470079 0.3957    ]


In [57]:
from keras import backend as K
def mean_absolute_percentage_error(y_true, y_pred):
    """
    计算平均绝对百分比误差（MAPR）
    """
    diff = K.abs((y_true - y_pred) / K.clip(K.abs(y_true), K.epsilon(), None))
    return 100. * K.mean(diff, axis=-1)

In [94]:
from keras.models import Sequential
from keras.layers import Dense

# Create the model
model = Sequential()

# Add the first hidden layer
model.add(Dense(1024, activation='relu', input_shape=(2,)))

# Add the second hidden layer
model.add(Dense(512, activation='relu'))

# Add the third hidden layer
model.add(Dense(256, activation='relu'))

# Add the output layer
model.add(Dense(1))

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error', metrics = ['MSE'])

# Print the model summary
model.summary()


Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_24 (Dense)            (None, 1024)              3072      
                                                                 
 dense_25 (Dense)            (None, 512)               524800    
                                                                 
 dense_26 (Dense)            (None, 256)               131328    
                                                                 
 dense_27 (Dense)            (None, 1)                 257       
                                                                 
Total params: 659,457
Trainable params: 659,457
Non-trainable params: 0
_________________________________________________________________


In [95]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(data_x,data_y, test_size=0.2, random_state=42)

# Print the shapes of the training and testing sets
print("Training set shape:", x_train.shape)
print("Testing set shape:", x_test.shape)
print(x_train)

Training set shape: (800000, 2)
Testing set shape: (200000, 2)
[[6.57300000e-01 9.19000000e-02]
 [9.74099300e-01 8.63500000e-05]
 [8.10640000e-01 6.00000000e-05]
 ...
 [7.69900000e-01 8.70000000e-03]
 [4.74345000e-01 4.35496000e-01]
 [4.36543054e-01 6.92000000e-06]]


In [96]:
model.fit(x_train, y_train, epochs=10, batch_size=32)


Epoch 1/10


25000/25000 [==============================] - 34s 1ms/step - loss: 7.8884e-05 - MSE: 7.8884e-05
Epoch 2/10
25000/25000 [==============================] - 34s 1ms/step - loss: 6.1995e-06 - MSE: 6.1995e-06
Epoch 3/10
25000/25000 [==============================] - 34s 1ms/step - loss: 3.8103e-06 - MSE: 3.8103e-06
Epoch 4/10
25000/25000 [==============================] - 34s 1ms/step - loss: 3.3968e-06 - MSE: 3.3968e-06
Epoch 5/10
25000/25000 [==============================] - 34s 1ms/step - loss: 2.4040e-06 - MSE: 2.4040e-06
Epoch 6/10
25000/25000 [==============================] - 34s 1ms/step - loss: 2.1271e-06 - MSE: 2.1271e-06
Epoch 7/10
25000/25000 [==============================] - 34s 1ms/step - loss: 2.1735e-06 - MSE: 2.1735e-06
Epoch 8/10
25000/25000 [==============================] - 34s 1ms/step - loss: 1.8213e-06 - MSE: 1.8213e-06
Epoch 9/10
25000/25000 [==============================] - 34s 1ms/step - loss: 1.7789e-06 - MSE: 1.7789e-06
Epoch 10/10
25000/25000 [==============

In [101]:
#predict
y_pred = model.predict(x_test)

#print(y_pred - y_test)


   1/6250 [..............................] - ETA: 1:05

6250/6250 [==============================] - 5s 777us/step


In [102]:
diff=[]
for i in range(y_pred.shape[0]):
    diff.append(abs(y_pred[i] - y_test[i]))
    #print(y_pred[i], y_test[i])
diff = np.array(diff)
print(diff)


[[0.00045705]
 [0.00092691]
 [0.00142419]
 ...
 [0.00108814]
 [0.00108433]
 [0.00054994]]


In [105]:
#print struct of diff
print(np.count_nonzero(diff < 0.001) / diff.shape[0] * 100, "%") 

67.597 %


In [110]:
input = np.array([85323,5323])
output = np.sum(input)
test_off = max(int(math.log10(input[0])+1), int(math.log10(input[1])+1))
input = input/10**test_off
print(input)
print(model.predict(np.array([input])*10**test_off))
print(output)

[0.85323 0.05323]
1/1 [==============================] - 0s 11ms/step
[[92712.664]]
90646


In [111]:
model.save('cve-2020-24213-v1.h5')
